language: objective-c
podfile: Podfile
osx_image: xcode8

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi
- gem install cocoapods
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- pod install

script:
- xcodebuild clean build -workspace PassportScanner.xcworkspace -scheme PassportScanner -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO
